In [1]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
dataset=[['사과','치즈','생수'],
['생수','호두','치즈','고등어'],
['수박','사과','생수'],
['생수','호두','치즈','옥수수']]

In [4]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_) #위에서 나온걸 보기 좋게 데이터프레임으로 변경

In [8]:
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)

In [10]:
association_rules(frequent_itemsets, metric="lift", min_threshold=1)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(생수),(사과),1.00,0.50,0.50,0.500000,1.000000,0.000,1.0
1,(사과),(생수),0.50,1.00,0.50,1.000000,1.000000,0.000,inf
2,(생수),(치즈),1.00,0.75,0.75,0.750000,1.000000,0.000,1.0
3,(치즈),(생수),0.75,1.00,0.75,1.000000,1.000000,0.000,inf
4,(생수),(호두),1.00,0.50,0.50,0.500000,1.000000,0.000,1.0
5,(호두),(생수),0.50,1.00,0.50,1.000000,1.000000,0.000,inf
6,(치즈),(호두),0.75,0.50,0.50,0.666667,1.333333,0.125,1.5
7,(호두),(치즈),0.50,0.75,0.50,1.000000,1.333333,0.125,inf
8,"(생수, 치즈)",(호두),0.75,0.50,0.50,0.666667,1.333333,0.125,1.5
9,"(생수, 호두)",(치즈),0.50,0.75,0.50,1.000000,1.333333,0.125,inf
10,"(치즈, 호두)",(생수),0.50,1.00,0.50,1.000000,1.000000,0.000,inf
11,(생수),"(치즈, 호두)",1.00,0.50,0.50,0.500000,1.000000,0.000,1.0
12,(치즈),"(생수, 호두)",0.75,0.50,0.50,0.666667,1.333333,0.125,1.5
13,(호두),"(생수, 치즈)",0.50,0.75,0.50,1.000000,1.333333,0.125,inf

In [2]:
### 항상도(lift) 1 보다 큰 경우 > 우연적 기회보다 높은 확률
### 항상도(lift) = 1 인 경우독립
### 항상도(lift) 1 보다 작은 경우 < 우연적 기회보다 낮은 확률